Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'testcase/')
src	= Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('Testcase', src, depend = ['RT_USING_TC'], CPPPATH = CPPPATH)

Return('group')
